version: "3.9"
services:
  api:
    build: .
    restart: always
    volumes:
      - ${PWD}/data:/app/data
      - ${PWD}/data/ingestData:/app/data/ingestData
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENV: ${PINECONE_ENV}
      S3_BUCKET_NAME: 'digitalimmortality-chat-history'
#      S3_BUCKET_NAME: 'digital-immortality-chat-history'
      S3_BUCKET_KEY: 'chat-history/history'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}